version: '2'
services:
  stats-generator:
    container_name: stats-generator
    build:
      context: stats-generator
      dockerfile: Dockerfile
    image: stats-generator:latest
    ports:
      - "8081:8081"
    networks:
      - gabella-network
  product-server:
    container_name: stats-manager
    build:
      context: stats-manager
      dockerfile: Dockerfile
    image: stats-manager:latest
    ports:
      - "8080:8080"
    networks:
      - gabella-network
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - gabella-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:2181"
    networks:
      - gabella-network
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - gabella-network
networks:
  gabella-network:
    driver: bridge